"""triggers_views

Revision ID: 7d56f4c68362
Revises: 7827d34bdc1b
Create Date: 2026-02-28 15:30:02.968592

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7d56f4c68362'
down_revision: Union[str, Sequence[str], None] = '7827d34bdc1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshots', sa.Column('views_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('snapshots', sa.Column('views_diff_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('snapshots', sa.Column('functions_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('snapshots', sa.Column('functions_diff_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('snapshots', sa.Column('triggers_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('snapshots', sa.Column('triggers_diff_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshots', 'triggers_diff_data')
    op.drop_column('snapshots', 'triggers_data')
    op.drop_column('snapshots', 'functions_diff_data')
    op.drop_column('snapshots', 'functions_data')
    op.drop_column('snapshots', 'views_diff_data')
    op.drop_column('snapshots', 'views_data')
    # ### end Alembic commands ###
